name: cicd_test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    #운영체제
    runs-on: ubuntu-latest
    
    #작업순서
    steps:
    - name: checkout
    #Git액션
      uses: actions/checkout@v2

    - name: build
      run: pip install -r requirements.txt
      
    - name: deploy
      run: python app.py prod
